namespace fmCommon
{
    enum PacketCategory
    {
        // 0 ~ 38개의 카테코리만 사용, 40부터는 서버 내부 용
        Test        = 0,
        Auth        = 1,        // 1: 128 ~ 255
        Lord        = 2,        // 2: 256 ~ 383
        Item        = 3,

        Shop        = 4,
        Mission     = 5,
        Explore     = 6,
        DragonTomb  = 7,
        Maze        = 8,
        Archive     = 9,
        Rank        = 10,
        IAB         = 11,
        DHeart      = 12,
        InDun       = 13,

        OP          = 36,
        Broadcast   = 37,
        MAX         = 38,
        Server      = 79,
    }

    public enum PacketType
    {
        PT_Unkwon = 0,
        PT_Test_RQ = 1,
        PT_Test_RS = 2,

        PT_Auth_Begin = PacketCategory.Auth << 7,
        PT_CA_Auth_Login_RQ,
        PT_CA_Auth_Login_RS,
        PT_CA_Auth_GetWorldList_RQ,
        PT_CA_Auth_GetWorldList_RS,
        PT_CG_Auth_GetConstant_RQ,
        PT_CG_Auth_GetConstant_RS,
        PT_Auth_End,

        PT_Lord_Begin = PacketCategory.Lord << 7,
        PT_CG_Lord_EnterWorld_RQ,
        PT_CG_Lord_EnterWorld_RS,
        PT_CG_Lord_CreateLord_RQ,
        PT_CG_Lord_CreateLord_RS,
        PT_CG_Lord_GetLord_RQ,
        PT_CG_Lord_GetLord_RS,
        PT_CG_Lord_SetStat_RQ,
        PT_CG_Lord_SetStat_RS,
        PT_Lord_End,

        PT_Item_Begin = PacketCategory.Item << 7,
        PT_CG_Item_GetList_RQ,
        PT_CG_Item_GetList_RS,
        PT_CG_Item_Equip_RQ,
        PT_CG_Item_Equip_RS,
        PT_CG_Item_Sell_RQ,
        PT_CG_Item_Sell_RS,
        PT_CG_Item_Remelt_RQ,
        PT_CG_Item_Remelt_RS,
        PT_CG_Item_Reroll_RQ,
        PT_CG_Item_Reroll_RS,
        PT_CG_Item_UpToAncient_RQ,
        PT_CG_Item_UpToAncient_RS,
        PT_CG_Item_PrevEnchantList_RQ,
        PT_CG_Item_PrevEnchantList_RS,
        PT_CG_Item_GetEnchantList_RQ,
        PT_CG_Item_GetEnchantList_RS,
        PT_CG_Item_Enchant_RQ,
        PT_CG_Item_Enchant_RS,
        PT_CG_Item_CreateMythic_RQ,
        PT_CG_Item_CreateMythic_RS,
        PT_CG_Item_AddOptToMythic_RQ,
        PT_CG_Item_AddOptToMythic_RS,
        PT_CG_Item_UseCombineCube_RQ,
        PT_CG_Item_UseCombineCube_RS,
        PT_CG_Item_RemoveRemelt_RQ,
        PT_CG_Item_RemoveRemelt_RS,
        PT_Item_End,

        PT_Shop_Begin = PacketCategory.Shop << 7,
        PT_CG_Shop_GetList_RQ,
        PT_CG_Shop_GetList_RS,
        PT_CG_Shop_BuyGood_RQ,
        PT_CG_Shop_BuyGood_RS,
        PT_CG_Shop_BuyItemWithSeal_RQ,
        PT_CG_Shop_BuyItemWithSeal_RS,
        PT_Shop_End,

        PT_CG_Mission_Begin = PacketCategory.Mission << 7,
        PT_CG_Mission_GetDailyList_RQ,
        PT_CG_Mission_GetDailyList_RS,
        PT_CG_Mission_Refresh_RQ,
        PT_CG_Mission_Refresh_RS,
        PT_CG_Mission_DailyComplete_RQ,
        PT_CG_Mission_DailyComplete_RS,
        PT_CG_Mission_DailyCounting_RQ,
        PT_CG_Mission_DailyCounting_RS,
        PT_CG_Mission_End,

        PT_Explore_Begin = PacketCategory.Explore << 7,
        PT_CG_Explore_GetList_RQ,
        PT_CG_Explore_GetList_RS,
        PT_CG_Explore_Search_RQ,
        PT_CG_Explore_Search_RS,
        PT_CG_Explore_Clear_RQ,
        PT_CG_Explore_Clear_RS,
        PT_CG_Explore_NextLevel_NT,
        PT_Explore_End,

        PT_DragonTomb = PacketCategory.DragonTomb << 7,
        PT_CG_DragonTomb_Refresh_RQ,
        PT_CG_DragonTomb_Refresh_RS,
        PT_CG_DragonTomb_Search_RQ,
        PT_CG_DragonTomb_Search_RS,
        PT_CG_DragonTomb_Clear_RQ,
        PT_CG_DragonTomb_Clear_RS,
        PT_CG_DragonTomb_Enter_RQ,
        PT_CG_DragonTomb_Enter_RS,
        PT_DragonTomb_End,

        PT_Maze_Begin = PacketCategory.Maze << 7,
        PT_CG_Maze_Enter_RQ,
        PT_CG_Maze_Enter_RS,
        PT_CG_Maze_Leave_RQ,
        PT_CG_Maze_Leave_RS,
        PT_CG_Maze_Search_RQ,
        PT_CG_Maze_Search_RS,
        PT_CG_Maze_Clear_RQ,
        PT_CG_Maze_Clear_RS,
        PT_CG_Maze_Sweep_RQ,
        PT_CG_Maze_Sweep_RS,
        PT_CG_Maze_Pvp_RQ,
        PT_CG_Maze_Pvp_RS,
        PT_CG_Maze_Pvp_NT,
        PT_Maze_End,

        PT_Archive_Begin = PacketCategory.Archive << 7,
        PT_CG_Archive_GetMailList_RQ,
        PT_CG_Archive_GetMailList_RS,
        PT_CG_Archive_TakeGood_RQ,
        PT_CG_Archive_TakeGood_RS,
        PT_Archive_End,

        PT_Rank_Begin = PacketCategory.Rank << 7,
        PT_CG_Rank_GetList_RQ,
        PT_CG_Rank_GetList_RS,
        PT_Rank_End,

        PT_IAB_Begin = PacketCategory.IAB << 7,
        PT_CG_IAB_Prepare_RQ,
        PT_CG_IAB_Prepare_RS,
        PT_CG_IAB_Cancel_RQ,
        PT_CG_IAB_Cancel_RS,
        PT_CG_IAB_Purchase_RQ,
        PT_CG_IAB_Purchase_RS,
        PT_Purchase_End,

        PT_DHeart_Begin = PacketCategory.DHeart << 7,
        PT_CG_DHeart_Enter_RQ,
        PT_CG_DHeart_Enter_RS,
        PT_CG_DHeart_Refresh_RQ,
        PT_CG_DHeart_Refresh_RS,
        PT_CG_DHeart_Search_RQ,
        PT_CG_DHeart_Search_RS,
        PT_CG_DHeart_Clear_RQ,
        PT_CG_DHeart_Clear_RS,
        PT_DHeart_End,

        PT_InDun_Begin = PacketCategory.InDun << 7,
        PT_CG_InDun_Refresh_RQ,
        PT_CG_InDun_Refresh_RS,
        PT_CG_InDun_Search_RQ,
        PT_CG_InDun_Search_RS,
        PT_CG_InDun_Clear_RQ,
        PT_CG_InDun_Clear_RS,
        PT_CG_InDun_OpenShortcut_RQ,
        PT_CG_InDun_OpenShortcut_RS,
        PT_InDun_End,

        PT_OP_Begin = PacketCategory.OP << 7,
        PT_OG_ModifyInformation_RQ,
        PT_OG_ModifyInformation_RS,
        PT_OG_Gift_RQ,
        PT_OG_Gift_RS,
        PT_OP_End,

        PT_Broadcast_Begin = PacketCategory.Broadcast << 7,
        PT_GC_Broadcast_Public_NT,
        PT_OC_Broadcast_Public_NT,
        PT_OC_Broadcast_Private_NT,
        PT_OA_Broadcast_SetNotice_RQ,
        PT_OA_Broadcast_SetNotice_RS,
        PT_CA_Broadcast_GetNotice_RQ,
        PT_CA_Broadcast_GetNotice_RS,
        PT_Broadcast_End,

        // Server 용
        PT_Server_Begin = PacketCategory.Server << 7,
        PT_Server_RegisterAtCenter_RQ,
        PT_Server_RegisterAtCenter_RS,
        PT_Server_ReadyToStart_RQ,
        PT_Server_ReadyToStart_RS,
        PT_Server_UpdateWorldState_NT,
        PT_AC_Server_GetWorldList_RQ,
        PT_AC_Server_GetWorldList_RS,
        PT_CA_Server_GetWorldList_NT,
        PT_Server_RegisterAtChat_RQ,
        PT_Server_RegisterAtChat_RS,

        PT_Server_End,
    }
}
